// Generated by https://quicktype.io

export interface UserLoginResponse{
    id:        string;
    username:  string;
    email:     string;
    nombre:    string;
    role:      string;
    createdAt: string;
    token:     string;
}
