// Generated by https://quicktype.io

export interface NewIssue {
    fechaProgramada:  string | null;
    anotaciones:      string;
    nombreEstacion:   string;
    nombreTrabajador: string;
    estado : string;
}
