// Generated by https://quicktype.io

export interface BikeUser {
    id:         string;
    createdAt:  string;
    email:      string;
    nombre:     string;
    username:   string;
    numTarjeta: null;
    pin:        null;
    saldo:      number;
}
