// Generated by https://quicktype.io

export interface UserBikeResponse {
    id: string;
    username: string;
    nombre: string;
    saldo: number;
}

// Generated by https://quicktype.io

export interface Recharge {
    recharge: number;
    pin: string;
}
